name: Deploy to Azure SWA

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag to deploy'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download release
        run: |
          # Download the release asset using GitHub CLI
          gh release download ${{ github.event.inputs.release_tag }} --repo ${{ github.repository }} --dir ./
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Unzip release
        run: |
          # Unzip the release asset
          unzip *.zip
          
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          app_location: "./public"
          api_location: "./server"
          skip_app_build: true