name: Deploy frontend to production

# Manual deployment trigger
on:
  workflow_dispatch:

env:
  FRONTEND_URL: https://lively-meadow-0abbd281e-preview.westus2.5.azurestaticapps.net/                  # set this to the frontend URL (for QR code generation)
  STATIC_APP_NAME: bendevfe                             # set this to the name of the frontend app on Azure Static Web Apps
  NODE_VERSION: 18
  APP_ENVIRONMENT: preview                              # set this to 'production' for production deployment or 'preview' for staging deployment.

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: build frontend
        working-directory: packages/frontend
        run: |
          npm ci
          npx nuxi build --preset=azure
      - name: Deploy frontend
        if: github.ref == 'refs/heads/main'
        working-directory: ./packages/frontend
        run: |
          npx @azure/static-web-apps-cli deploy .output/public/ --api-location .output/server/ --app-name=${{ env.STATIC_APP_NAME }} --env ${{ env.APP_ENVIRONMENT }} --api-language=node --api-version=${{ env.NODE_VERSION }} --deployment-token  ${{ secrets.AZURE_SWA_DEPLOYMENT_TOKEN }}
      # - name: Upload build artifact
      #   uses: actions/upload-artifact@v4.3.3
      #   with:
      #     name: packages
      #     path: packages/frontend/.output/**
