name: Deploy frontend to production

# Manual deployment trigger
on:
  workflow_dispatch:
    inputs:
      FRONTEND_URL:
        description: 'Frontend URL (for QR code generation)'
        required: true
        default: 'https://lively-meadow-0abbd281e-preview.westus2.5.azurestaticapps.net/'
      APP_NAME:
        description: 'Frontend app name on Azure Static Web Apps'
        required: true
        default: 'bendevfe'
      APP_ENVIRONMENT:
        type: choice
        description: "Deployment environment, eg. 'preview' or 'production'"
        required: true
        options:
          - 'preview'
          - 'production'
        default: 'preview'
      BUMP_VERSION:
        type: choice
        description: "Bump version, eg. 'major', 'minor', or 'patch'"
        required: true
        options:
          - 'major'
          - 'minor'
          - 'patch'
        default: 'patch'

env:
  FRONTEND_URL: ${{ github.event.inputs.FRONTEND_URL }}       # set this to the frontend URL (for QR code generation)
  STATIC_APP_NAME: ${{ github.event.inputs.APP_NAME }}        # set this to the name of the frontend app on Azure Static Web Apps
  NODE_VERSION: 18
  APP_ENVIRONMENT: ${{ github.event.inputs.APP_ENVIRONMENT }} # set this to 'production' for production deployment or 'preview' for staging deployment.

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        id: bump_version
        uses: anothrNick/github-tag-action@v1 # Don't use @master or @v1 unless you're happy to test the latest version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
          WITH_V: true
          DEFAULT_BUMP: ${{ github.event.inputs.BUMP_VERSION }}
      - name: build frontend
        working-directory: packages/frontend
        env:
          APP_VERSION: ${{ steps.bump_version.outputs.new_tag }}
        run: |
          npm ci
          npx nuxi build --preset=azure
      - name: Deploy frontend
        if: github.ref == 'refs/heads/main'
        working-directory: ./packages/frontend
        run: |
          npx @azure/static-web-apps-cli deploy .output/public/ --api-location .output/server/ --app-name=${{ env.STATIC_APP_NAME }} --env ${{ env.APP_ENVIRONMENT }} --api-language=node --api-version=${{ env.NODE_VERSION }} --deployment-token  ${{ secrets.AZURE_SWA_DEPLOYMENT_TOKEN }}
      - name: Upload build artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: ${{ env.STATIC_APP_NAME }}-${{ steps.bump_version.outputs.new_tag }}
          path: packages/frontend/.output/**
